project_id = "jkzrpjlfdsxvcfwhuoey"

[functions.send-contact-notification]
verify_jwt = false

[functions.send-sample-request-notification]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.rag-chat]
verify_jwt = false

[functions.seed-knowledge-base]
verify_jwt = false

[functions.seed-knowledge-base-bulk]
verify_jwt = false
